name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  integration:
    name: Selenium Integration Tests
    runs-on: ubuntu-latest
    needs: build
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Start server
        # Launch your app in the background
        run: |
          nohup node src/server.js & 
          # wait for it to be up
          sleep 5

      - name: Run Selenium tests
        # 'ci' passes a flag so tests target the CI service
        run: node tests/SeleniumTest.mjs ci
