name: Node.js Selenium Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Create build artifact
      run: tar -czf www-build.tar.gz src/ tests/ package.json package-lock.json

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: www-build
        path: www-build.tar.gz

  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      selenium:
        image: seleniarm/standalone-chromium:latest
        ports:
          - 4444:4444
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: www-build
    - name: Extract artifact
      run: tar -xzf www-build.tar.gz
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests
      run: npm test
    - name: Start Node.js server
      run: |
        # Start the server in the background
        node src/server.js &
        # Give it a moment to start up
        sleep 5
    - name: Wait for Selenium service to be ready
      run: |
        while ! curl --silent --fail http://selenium:4444/wd/hub/status > /dev/null; do
          echo "Waiting for Selenium..."
          sleep 2
        done
        echo "Selenium is up!"

    - name: Run Selenium integration tests
      run: node tests/SeleniumTest.mjs github